global:
  scrape_interval: 15s
#  evaluation_interval: 15s # rules
  
#rule_files:
#  - "first.rule"
#  - "second.rule"
scrape_configs:
  - job_name: 'hivemq broker'
    scrape_interval: 5s
    metrics_path: '/metrics'
    static_configs:
      - targets: ['hivemq:9399']
      
  - job_name: 'data validation'
    # Override the global default and scrape targets from this job every 5 seconds.
    scrape_interval: 5s
    static_configs:
      - targets: ['data-validation:9091']
      

